from PyQt5 import QtCore, QtWidgets


class Ui_AiSettingsDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("AiSettingsDialog")
        Dialog.resize(540, 260)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.txtHost = QtWidgets.QLineEdit(self.groupBox)
        self.txtHost.setObjectName("txtHost")
        self.formLayout.addRow("Host：", self.txtHost)
        self.txtApiKey = QtWidgets.QLineEdit(self.groupBox)
        self.txtApiKey.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtApiKey.setObjectName("txtApiKey")
        self.formLayout.addRow("API Key：", self.txtApiKey)
        self.txtModel = QtWidgets.QLineEdit(self.groupBox)
        self.txtModel.setObjectName("txtModel")
        self.formLayout.addRow("模型：", self.txtModel)
        self.verticalLayout.addWidget(self.groupBox)
        self.labHint = QtWidgets.QLabel(Dialog)
        self.labHint.setWordWrap(True)
        self.labHint.setObjectName("labHint")
        self.verticalLayout.addWidget(self.labHint)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnClear = QtWidgets.QPushButton(Dialog)
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout.addWidget(self.btnClear)
        self.horizontalLayout.addStretch(1)
        self.btnSubmit = QtWidgets.QPushButton(Dialog)
        self.btnSubmit.setObjectName("btnSubmit")
        self.horizontalLayout.addWidget(self.btnSubmit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("AiSettingsDialog", "AI 设置"))
        self.groupBox.setTitle(_translate("AiSettingsDialog", "OpenAI 兼容接口配置"))
        self.txtHost.setPlaceholderText(_translate("AiSettingsDialog", "例如：https://api.openai.com/v1 或你的兼容服务地址"))
        self.txtApiKey.setPlaceholderText(_translate("AiSettingsDialog", "请输入 API Key"))
        self.txtModel.setPlaceholderText(_translate("AiSettingsDialog", "例如：gpt-4o-mini / deepseek-chat / qwen-max"))
        self.labHint.setText(_translate("AiSettingsDialog", "未配置 API Key / Host / 模型 时，AI 写脚本和 AI 分析日志功能会自动禁用。"))
        self.btnClear.setText(_translate("AiSettingsDialog", "清空"))
        self.btnSubmit.setText(_translate("AiSettingsDialog", "保存"))
