from PyQt5 import QtCore, QtWidgets


class Ui_CustomDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1320, 820)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")

        self.mainSplitter = QtWidgets.QSplitter(Dialog)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setObjectName("mainSplitter")

        self.groupBox_2 = QtWidgets.QGroupBox(self.mainSplitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.editorLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.editorLayout.setObjectName("editorLayout")

        self.formLayout = QtWidgets.QGridLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtJsName = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtJsName.setObjectName("txtJsName")
        self.formLayout.addWidget(self.txtJsName, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.txtJsFileName = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtJsFileName.setObjectName("txtJsFileName")
        self.formLayout.addWidget(self.txtJsFileName, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.txtBak = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtBak.setObjectName("txtBak")
        self.formLayout.addWidget(self.txtBak, 1, 1, 1, 3)
        self.editorLayout.addLayout(self.formLayout)

        self.aiGroup = QtWidgets.QGroupBox(self.groupBox_2)
        self.aiGroup.setObjectName("aiGroup")
        self.aiLayout = QtWidgets.QVBoxLayout(self.aiGroup)
        self.aiLayout.setObjectName("aiLayout")
        self.labAiStatus = QtWidgets.QLabel(self.aiGroup)
        self.labAiStatus.setWordWrap(True)
        self.labAiStatus.setObjectName("labAiStatus")
        self.aiLayout.addWidget(self.labAiStatus)
        self.txtAiPrompt = QtWidgets.QPlainTextEdit(self.aiGroup)
        self.txtAiPrompt.setObjectName("txtAiPrompt")
        self.aiLayout.addWidget(self.txtAiPrompt)
        self.aiButtonLayout = QtWidgets.QHBoxLayout()
        self.aiButtonLayout.setObjectName("aiButtonLayout")
        self.btnAiPromptTemplate = QtWidgets.QPushButton(self.aiGroup)
        self.btnAiPromptTemplate.setObjectName("btnAiPromptTemplate")
        self.aiButtonLayout.addWidget(self.btnAiPromptTemplate)
        self.btnAiGenerate = QtWidgets.QPushButton(self.aiGroup)
        self.btnAiGenerate.setObjectName("btnAiGenerate")
        self.aiButtonLayout.addWidget(self.btnAiGenerate)
        self.aiButtonLayout.addStretch(1)
        self.aiLayout.addLayout(self.aiButtonLayout)
        self.editorLayout.addWidget(self.aiGroup)

        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.editorLayout.addWidget(self.label_2)
        self.txtJsData = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtJsData.setObjectName("txtJsData")
        self.editorLayout.addWidget(self.txtJsData)

        self.actionLayout = QtWidgets.QHBoxLayout()
        self.actionLayout.setObjectName("actionLayout")
        self.btnClear = QtWidgets.QPushButton(self.groupBox_2)
        self.btnClear.setObjectName("btnClear")
        self.actionLayout.addWidget(self.btnClear)
        self.actionLayout.addStretch(1)
        self.btnSubmit = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSubmit.setObjectName("btnSubmit")
        self.actionLayout.addWidget(self.btnSubmit)
        self.editorLayout.addLayout(self.actionLayout)

        self.sidebarWidget = QtWidgets.QWidget(self.mainSplitter)
        self.sidebarWidget.setObjectName("sidebarWidget")
        self.sidebarLayout = QtWidgets.QVBoxLayout(self.sidebarWidget)
        self.sidebarLayout.setObjectName("sidebarLayout")
        self.sidebarLayout.setContentsMargins(0, 0, 0, 0)

        self.topSplitter = QtWidgets.QSplitter(self.sidebarWidget)
        self.topSplitter.setOrientation(QtCore.Qt.Vertical)
        self.topSplitter.setObjectName("topSplitter")

        self.groupBox = QtWidgets.QGroupBox(self.topSplitter)
        self.groupBox.setObjectName("groupBox")
        self.groupBoxLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.groupBoxLayout.setObjectName("groupBoxLayout")
        self.tabCustomList = QtWidgets.QTableWidget(self.groupBox)
        self.tabCustomList.setObjectName("tabCustomList")
        self.tabCustomList.setColumnCount(0)
        self.tabCustomList.setRowCount(0)
        self.groupBoxLayout.addWidget(self.tabCustomList)

        self.groupBox_3 = QtWidgets.QGroupBox(self.topSplitter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox3Layout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.groupBox3Layout.setObjectName("groupBox3Layout")
        self.tabCustomHookList = QtWidgets.QTableWidget(self.groupBox_3)
        self.tabCustomHookList.setObjectName("tabCustomHookList")
        self.tabCustomHookList.setColumnCount(0)
        self.tabCustomHookList.setRowCount(0)
        self.groupBox3Layout.addWidget(self.tabCustomHookList)

        self.sidebarLayout.addWidget(self.topSplitter)

        self.groupBox_4 = QtWidgets.QGroupBox(self.sidebarWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.tipLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.tipLayout.setObjectName("tipLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.tipLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.tipLayout.addWidget(self.label_4)
        self.sidebarLayout.addWidget(self.groupBox_4)

        self.verticalLayout.addWidget(self.mainSplitter)

        self.retranslateUi(Dialog)
        self.mainSplitter.setSizes([860, 440])
        self.topSplitter.setSizes([320, 240])
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "自定义"))
        self.groupBox.setTitle(_translate("Dialog", "脚本仓库"))
        self.groupBox_3.setTitle(_translate("Dialog", "当前使用脚本"))
        self.groupBox_2.setTitle(_translate("Dialog", "脚本编辑器"))
        self.label.setText(_translate("Dialog", "脚本别名："))
        self.label_6.setText(_translate("Dialog", "脚本名："))
        self.label_5.setText(_translate("Dialog", "备注："))
        self.aiGroup.setTitle(_translate("Dialog", "AI 助手"))
        self.labAiStatus.setText(_translate("Dialog", "AI 状态：未检测"))
        self.txtAiPrompt.setPlaceholderText(_translate("Dialog", "例如：帮我 hook okhttp3 请求和响应，打印 URL、Header、Body，并保留 call_funs.demo 作为主动调用样例。"))
        self.btnAiPromptTemplate.setText(_translate("Dialog", "填充提示词模板"))
        self.btnAiGenerate.setText(_translate("Dialog", "AI 生成 Hook"))
        self.label_2.setText(_translate("Dialog", "Hook 脚本："))
        self.btnClear.setText(_translate("Dialog", "清空"))
        self.btnSubmit.setText(_translate("Dialog", "保存脚本"))
        self.groupBox_4.setTitle(_translate("Dialog", "操作提示"))
        self.label_3.setText(_translate("Dialog", "双击脚本仓库中的脚本可进入编辑；右键可删除或加入当前 Hook 列表。关闭窗口后，当前使用脚本会同步到主界面的 Hook 列表。"))
        self.label_4.setText(_translate("Dialog", "AI 功能会按照 fridaUiTools custom 模块格式生成脚本；未配置 API Key / Host / 模型时，将自动禁用 AI 按钮。"))
