# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fart.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FartDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(959, 452)
        self.gridLayout_6 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txtClasses = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtClasses.setObjectName("txtClasses")
        self.gridLayout_5.addWidget(self.txtClasses, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnSelectClasses = QtWidgets.QPushButton(self.frame)
        self.btnSelectClasses.setMinimumSize(QtCore.QSize(120, 40))
        self.btnSelectClasses.setMaximumSize(QtCore.QSize(120, 40))
        self.btnSelectClasses.setObjectName("btnSelectClasses")
        self.gridLayout_3.addWidget(self.btnSelectClasses, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 0, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnSubmitFridaFartClass = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSubmitFridaFartClass.setMinimumSize(QtCore.QSize(120, 40))
        self.btnSubmitFridaFartClass.setMaximumSize(QtCore.QSize(120, 40))
        self.btnSubmitFridaFartClass.setObjectName("btnSubmitFridaFartClass")
        self.gridLayout_2.addWidget(self.btnSubmitFridaFartClass, 0, 0, 1, 1)
        self.btnSubmitFridaFart = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSubmitFridaFart.setMinimumSize(QtCore.QSize(120, 40))
        self.btnSubmitFridaFart.setMaximumSize(QtCore.QSize(120, 40))
        self.btnSubmitFridaFart.setObjectName("btnSubmitFridaFart")
        self.gridLayout_2.addWidget(self.btnSubmitFridaFart, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnSubmitFartClass = QtWidgets.QPushButton(self.groupBox_4)
        self.btnSubmitFartClass.setEnabled(True)
        self.btnSubmitFartClass.setMinimumSize(QtCore.QSize(120, 40))
        self.btnSubmitFartClass.setMaximumSize(QtCore.QSize(120, 40))
        self.btnSubmitFartClass.setObjectName("btnSubmitFartClass")
        self.gridLayout_4.addWidget(self.btnSubmitFartClass, 0, 0, 1, 1)
        self.btnSubmitFart = QtWidgets.QPushButton(self.groupBox_4)
        self.btnSubmitFart.setEnabled(True)
        self.btnSubmitFart.setMinimumSize(QtCore.QSize(120, 40))
        self.btnSubmitFart.setMaximumSize(QtCore.QSize(120, 40))
        self.btnSubmitFart.setObjectName("btnSubmitFart")
        self.gridLayout_4.addWidget(self.btnSubmitFart, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 2, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "fart"))
        self.groupBox_3.setTitle(_translate("Dialog", "类列表"))
        self.btnSelectClasses.setText(_translate("Dialog", "选择文件"))
        self.groupBox_2.setTitle(_translate("Dialog", "frida FART"))
        self.btnSubmitFridaFartClass.setText(_translate("Dialog", "fart处理类列表"))
        self.btnSubmitFridaFart.setText(_translate("Dialog", "fart完整调用"))
        self.groupBox_4.setTitle(_translate("Dialog", "rom FART"))
        self.btnSubmitFartClass.setText(_translate("Dialog", "fart处理类列表"))
        self.btnSubmitFart.setText(_translate("Dialog", "fart完整调用"))
        self.groupBox.setTitle(_translate("Dialog", "提示"))
        self.label.setText(_translate("Dialog", "1、frida FART是完全使用frida实现的简易fart。rom FART需要使用特定的rom，否则无法访问到FART的api"))
        self.label_2.setText(_translate("Dialog", "2、fart处理类列表会只处理指定类的所有函数主动调用"))
        self.label_5.setText(_translate("Dialog", "3、fart完整调用会遍历所有ClassLoader查询所有DexFile的所有类，主动调用所有函数，所以非常慢"))

