# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'port.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Port(object):
    def setupUi(self, Port):
        Port.setObjectName("Port")
        Port.resize(372, 212)
        self.gridLayout_2 = QtWidgets.QGridLayout(Port)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Port)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.txtPort = QtWidgets.QLineEdit(self.groupBox)
        self.txtPort.setObjectName("txtPort")
        self.gridLayout.addWidget(self.txtPort, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.txtFridaName = QtWidgets.QLineEdit(self.groupBox)
        self.txtFridaName.setText("")
        self.txtFridaName.setObjectName("txtFridaName")
        self.gridLayout.addWidget(self.txtFridaName, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnClear = QtWidgets.QPushButton(self.groupBox)
        self.btnClear.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout.addWidget(self.btnClear)
        self.btnSubmit = QtWidgets.QPushButton(self.groupBox)
        self.btnSubmit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btnSubmit.setObjectName("btnSubmit")
        self.horizontalLayout.addWidget(self.btnSubmit)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Port)
        QtCore.QMetaObject.connectSlotsByName(Port)

    def retranslateUi(self, Port):
        _translate = QtCore.QCoreApplication.translate
        Port.setWindowTitle(_translate("Port", "连接配置"))
        self.groupBox.setTitle(_translate("Port", "设置"))
        self.txtPort.setText(_translate("Port", "6666"))
        self.label_4.setText(_translate("Port", "端口："))
        self.label_5.setText(_translate("Port", "frida_name："))
        self.btnClear.setText(_translate("Port", "清空"))
        self.btnSubmit.setText(_translate("Port", "提交"))
